_prefs: 
  mapid: ruben.6d3d9d24
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.7488
  - 40.7745
  - 17
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 10
name: Special-co-A-NYC
source: "mapbox:///mapbox.mapbox-streets-v5,ruben.bbfdc6ab"
styles: 
  - style.mss
template: ''
